### ISSUE TITLE
Drawer API?

### ISSUE THREAD

**Issue by Tim-W** [react-native-material-design/react-native-material-design#109]
In the (new?) Drawer API, a list of children is required. What do I put here? I cannot find it in the example project nor in the documentation. Better documentation would be great.

![alt text](https://i.gyazo.com/339cf2a31a97228e447bd8455e389201.png "Logo Title Text 1")

**Comment by Ehesp** [comment]
Children is just whatever is within the component:

```
<Drawer>
    <View>
        <Text>Children</Text>
    </View>
</Drawer>
```

**Comment by SelaOren** [comment]
How do you make it appear?
