### ISSUE TITLE
Using navigator to Welcome component

### ISSUE THREAD

**Issue by avishayil** [react-native-material-design/react-native-material-design#13]
Hi,
I would like to be able to use the navigator FROM the welcome screen, in order to change scene from the screen itself to another screen.

Basically I have a list of cards on the Welcome screen, which the link on each card supposed to go to another component (MyComponent.js, placed on the scenes folder), with different props.

Any ideas?

**Comment by Ehesp** [comment]
Hello

In the demo, the navigator is created by reference into the context of the app, meaning you can access it from any child component of the `index.android.js` file. In this case, the entire app.

https://github.com/react-native-material-design/demo-app/blob/master/src/scenes/Navigation.js#L81

The link above shows how you can grab it from context, and use it wherever you like.

**Comment by avishayil** [comment]
How can I access them outside of the render() function?

**Comment by Ehesp** [comment]
Same way you'd access props or state. 

```
const { navigator } = this.context

navigator.pop();

```

**Comment by avishayil** [comment]
Thanks for the swift response and help!

I tried too hard and couldn't figured it out, i'm sure i'm missing here something.
Here's my welcome screen code, i'm using react-native-gifted-listview module as my refreshable list component.

When i'm trying to console.log(navigator) i'm getting undefined.
Maybe you'll be able to help me out with this.

````javascript
import React, { Component, View, Text, Image, IntentAndroid } from 'react-native';
import { Card, Button, COLOR, TYPO } from 'react-native-material-design';

import AppStore from '../stores/AppStore';

var API_URL = 'http://www.geektime.co.il/appApi/json.php';
var GiftedListView = require('react-native-gifted-listview');
var Post = require ('./Post');
var connError = 0;

export default class Welcome extends Component {
  _onFetch(page = 1, callback, options) {
    var data = [];
    function timeout(ms, promise) {
      return new Promise(function(resolve, reject) {
        setTimeout(function() {
            reject(new Error("timeout"))
        }, ms)
        promise.then(resolve, reject)
      })
    }

    timeout(5000,fetch(API_URL + '?page=' + page)
      .then((response) => response.json())
      .then((responseData) => {
        if (connError == 1) {
          connError = 0;
        }
        data = responseData.posts;
        page++;
          callback(data);
      }).catch((error) => {
        if (connError == 0) {
            connError = 1;
        }
        callback(null);
      }).done()
    )
  }
    _renderCardView(rowData) {
      const navigator = this.context;
      const theme = AppStore.getState().theme;
      return (
        <View>
            <Card>
                <Card.Media
                    image={<Image source={{uri:rowData.image}}/>}
                    overlay
                >
                    <Text style={[TYPO.paperFontHeadline, COLOR.paperGrey50]}>{rowData.title}</Text>
                    <Text style={[TYPO.paperSubhead, COLOR.paperGrey50]}>{rowData.author}</Text>
                </Card.Media>
                <Card.Body>
                    <Text>{rowData.excerpt}</Text>
                </Card.Body>
                <Card.Actions position="left">
                    <Button primary={theme} value="To the article" onPress={() => console.log(navigator) } />
                </Card.Actions>
            </Card>
        </View>
      )
    }
    render() {
        return (
          <GiftedListView
            rowView={this._renderCardView}
            onFetch={this._onFetch}
            firstLoader={true} // display a loader for the first fetching
            pagination={true} // enable infinite scrolling using touch to load more
            refreshable={true} // enable pull-to-refresh for iOS and touch-to-refresh for Android
            withSections={false} // enable sections
            customStyles={{
              refreshableView: {
                backgroundColor: '#eee',
              },
            }}

            PullToRefreshViewAndroidProps={{
              colors: ['#ff0000', '#00ff00', '#0000ff'],
              progressBackgroundColor: '#c8c7cc',
            }}
          />
        );
    }

}

      )
    }
    render() {
        return (
          <GiftedListView
            rowView={this._renderCardView}
            onFetch={this._onFetch}
            firstLoader={true} // display a loader for the first fetching
            pagination={true} // enable infinite scrolling using touch to load more
            refreshable={true} // enable pull-to-refresh for iOS and touch-to-refresh for Android
            withSections={false} // enable sections
            customStyles={{
              refreshableView: {
                backgroundColor: '#eee',
              },
            }}

            PullToRefreshViewAndroidProps={{
              colors: ['#ff0000', '#00ff00', '#0000ff'],
              progressBackgroundColor: '#c8c7cc',
            }}
          />
        );
    }
}

**Comment by Ehesp** [comment]
No problem!

`this.context` is an object, containing the navigator and drawer references. You need to do either:

`const { navigator } = this.context;` or
`const navigator = this.context.navigator;`

**Comment by avishayil** [comment]
Tried them both, nothing works. headache.
Mind if I wrap the whole code in a zip and send it to you?

**Comment by Ehesp** [comment]
Ah wait, you're missing something:

```
    static contextTypes = {
        navigator: PropTypes.object.isRequired
    };
```

That should work now, I hope ha.

**Comment by avishayil** [comment]
Can't find variable: PropTypes

**Comment by Ehesp** [comment]
You need to import it...

`import React, { Component, **PropTypes**, View, Text, Image, IntentAndroid } from 'react-native';`

**Comment by avishayil** [comment]
Works, but returns the WorkerNavigator instead of the navigator.

**Comment by Ehesp** [comment]
Erm, WorkerNavigator? Can you dump the console.log of the navigator here?

**Comment by avishayil** [comment]
_renderCardView(rowData) {
      const theme = AppStore.getState().theme;
      console.log(navigator); // prints the following.
      return (
        <View>
            <Card>
                <Card.Media
                    image={<Image source={{uri:rowData.image}}/>}
                    overlay
                >
                    <Text style={[TYPO.paperFontHeadline, COLOR.paperGrey50]}>{rowData.title}</Text>
                    <Text style={[TYPO.paperSubhead, COLOR.paperGrey50]}>{rowData.author}</Text>
                </Card.Media>
                <Card.Body>
                    <Text>{rowData.excerpt}</Text>
                </Card.Body>
                <Card.Actions position="left">
                    <Button primary={theme} value="Read" />
                </Card.Actions>
            </Card>
        </View>
      )
    }

![screen shot 2016-01-04 at 3 02 52 pm](https://cloud.githubusercontent.com/assets/827024/12090099/4b076f5a-b2f4-11e5-8a74-8c0b3418abbf.png)

**Comment by Ehesp** [comment]
Okay so I went about and tackled this... 

https://github.com/react-native-material-design/demo-app#navigate

Custom implementation which is pretty flexible. Might make it into a lib but could do with testing on it first :)

**Comment by arpu** [comment]
with more cards i get Cannot read property '_currentElement' of null

when i use const { navigator } = this.context;

**Comment by Ehesp** [comment]
Could you show me the full code?

**Comment by arpu** [comment]
http://lpaste.net/148531

**Comment by Salakar** [comment]
@arpu can you also show us your routes file please

**Comment by arpu** [comment]
is the routes file from the demo-app  nothing changed

**Comment by Ehesp** [comment]
Could you try replacing the Button with this:

`<Button primary={theme} value="Read this" onPress={() =>  { navigator.forward() }} />`

If that doesn't work, can you paste the output of `this.context.navigator` for us... cheers

**Comment by avishayil** [comment]
TypeError: Cannot read property 'navigator' of undefined(…)
ExceptionsManager.js:63 Cannot read property '_currentElement' of nullhandleException @ ExceptionsManager.js:63handleError @ InitializeJavaScriptAppEngine.js:80ErrorUtils.reportFatalError @ error-guard.js:28guard @ MessageQueue.js:40callFunctionReturnFlushedQueue @ MessageQueue.js:81onmessage @ debuggerWorker.js:39

**Comment by Ehesp** [comment]
Try changing:
`_renderCardView(rowData) {`

to:
`_renderCardView = (rowData) => {`

**Comment by avishayil** [comment]
This solves the issue.

**Comment by Ehesp** [comment]
Okay so this is because within `_renderCardView(rowData) {`, the class (`this`) isn't bound into that function.  To get around this you could do something in the constructor like:

```
constructor() {
    super();
    this._renderCardView = this._renderCardView.bind(this);
}
```

However, that to me is a bit stinky, so doing:

`_renderCardView = (rowData) => {` is a cleaner way to bind `this`, using the arrow function:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by arpu** [comment]
works for me too thx

**Comment by Salakar** [comment]
Closing issue as this is resolved.
