### ISSUE TITLE
fading actionbar

### ISSUE THREAD

**Issue by arpu** [react-native-material-design/react-native-material-design#14]
like this https://github.com/ManuelPeinado/FadingActionBar

and in the movie and music play store google app

is this possible ?

**Comment by Salakar** [comment]
Should be doable, we'll have a look and get back to you :)

**Comment by Ehesp** [comment]
I'm sure it will be, but need to think about how the toolbar will cope with this. Currently it's sat at the top of everything as a "master", something like this would need to override it, or provide a way to override it for a current scene... Shall think.

**Comment by Ehesp** [comment]
I added this as an issue here, https://github.com/facebook/react-native/issues/5177, however I'm thinking it's not possibly to do like this.

One potential solution is that with the custom Navigate class in the demo, you could do something like so:

```
Navigate.to('route', {
    name: 'Some route',
    navigationBar: <SomeOtherComponent />
});
```

Then in our Toolbar component, do something like:

```
render() {
   const { navigator } = this.context;

   if (navigator.navigationBar) {
       return  navigator.navigationBar;
   }

   return <Toolbar....../>
}
```

This however, means the whole demo-app itself is very tightly attached to:

- The Navigate class
- The demo app implementing the Toolbar in this way.

Yet at the same time, all we need to do for the core lib is provide the toolbar... how you implement it in your own setup is your issue I suppose.

**Comment by bozzmob** [comment]
Hi @arpu @Salakar @Ehesp It is possible. And there is already a react native implementation [react-native-parallax-scroll-view](https://github.com/jaysoo/react-native-parallax-scroll-view). It's really a great implementation. I have tried it and used it. :)
It is an actively maintained repo.

**Comment by Ehesp** [comment]
Looks good but doesn't seem very "Material", especially how it doesn't fade. Shall look into it a bit more.

**Comment by arpu** [comment]
@Ehesp you workin on this?

**Comment by arpu** [comment]
can be closed? works perfect with  react-native-parallax-scroll-view.
