### ISSUE TITLE
Button onPress/onLongPress trigger setState warning

### ISSUE THREAD

**Issue by pewh** [react-native-material-design/react-native-material-design#19]
I got yellow-warning `setState` on RN 0.16 when trigger `onPress/onLongPress` event.
```
  handleSubmit = () => {
    this.props.onSubmit(this.state)
  }
...
      <Button
        onPress={this.handleSubmit.bind(this)}
        onLongPress={this.handleSubmit.bind(this)}
        primary='googleRed'
        theme='dark'
        raised={true}
        value='Save'
      />
```

But this code below doesn't throw any warning.

```
      <TouchableOpacity onPress={this.handleSubmit.bind(this)}>
        <Text>Save</Text>
      </TouchableOpacity>
```

Btw, [this button](https://github.com/APSL/react-native-button) also show warning as same like react-native-material-design button do.

**Comment by Ehesp** [comment]
That's because you're doing it wrong I believe. You're calling the method when the component is being rendered, not when it's clicked:
```
<Button
        onPress={() => this.handleSubmit }
        onLongPress={() => this.handleSubmit }
        primary='googleRed'
        theme='dark'
        raised={true}
        value='Save'
      />
```

**Comment by pewh** [comment]
`<Button onPress={() => this.handleSubmit }>` doesn't trigger function `handleSubmit`.
It should be `<Button onPress={() => this.handleSubmit() }>`. Unfortunately, it still throw warning :/

**Comment by Ehesp** [comment]
Hmm, can I see your entire component? What Android API are you running? And are you using master or 3.1?

**Comment by pewh** [comment]
See this [gist](https://gist.github.com/pewh/f3dc58827a30489b8219) at line 91, 95, and 96 (LoginForm.js).
Tested on Android 4.1 (Genymotion) and Android 4.4 (real device). Using RNMD@0.3.1.

And I also had refactor `this.props.onSubmit(this.state)` (check my gist), but problem still occured.

**Comment by Salakar** [comment]
@pewh can we see the code for `this.props.onSubmit(usernameValue, passwordValue)` - that function, also try commenting out that row and see if you still get the issue, then we know if it's that or not

**Comment by pewh** [comment]
I have figure out the problem. This is not RNMD issue, but my code.
```
function handleSubmit (props) {
  redirectToHomeRoute(props) // this will unmount current component
  this.setState({ foo: 'bar' }) // trigger setState warning
}
```

I'm just curios why there's no warning on `<TouchableOpacity onPress={handleSubmit}>...</TouchableOpacity>`. But at least all goes well. Thanks for the time.
