### ISSUE TITLE
[IOS] ToggleIcon doesn't work

### ISSUE THREAD

**Issue by maxs15** [react-native-material-design/react-native-material-design#20]
Hi,
Awesome library ! Keep up the good work ;)
I have some trouble to try out the ToggleIcon component on IOS.
My icon is displayed but I don't have any ripple effect on click, is there an issue ?
The opacity doesn't seems to work as well..

Here is my code
```
<IconToggle color="paperGrey900" onPress={this.toggleFavorite}>
     <Icon name="star" size={50} color="#F8E71C" opacity={.6}/>
</IconToggle>
```

Thanks

**Comment by Ehesp** [comment]
Hey, cheers!

Which version of iOS are you on? Will test it out. Also opacity isn't a prop for Icon, you should be able to pass it in via the style prop though.

**Comment by maxs15** [comment]
I tried on simulator with IOS 9.1, thanks !
Arf, I'm sorry I don't know where I've seen such a property^^

**Comment by Salakar** [comment]
@maxs15 could you try use the master branch rather than the current release and see if the ripple works? I think we fixed a couple of ripple issues since the last release.

**Comment by maxs15** [comment]
Doesn't work on master either.
What about you guys, does it work on your side ?

**Comment by Ehesp** [comment]
Just pushed up a fix, hopefully: https://github.com/react-native-material-design/react-native-material-design/commit/f9af5bec7724987d3425f62240bb4af24876a6fd

Can you try on master again for me?
