### ISSUE TITLE
Unrecognized font family 'Roboto,Noto,sans-serif

### ISSUE THREAD

**Issue by stevenxiale** [react-native-material-design/react-native-material-design#28]
Unrecognized font family 'Roboto,Noto,sans-serif'

**Comment by Ehesp** [comment]
?? 

Anymore information? What device? What platform? What RN version?

**Comment by solchea** [comment]
I'm getting the same error while trying to use in an iOS app. I followed these instructions and verified the fonts are being loaded but still no luck.

http://stackoverflow.com/questions/29310828/use-custom-font-in-react-native

**Comment by stevenxiale** [comment]
ios: iphone6  react-native: 0.18.0   When use some component which use Roboto,Noto,sans-serif as font family, it will throws error.

**Comment by stevenxiale** [comment]
such as subhead

**Comment by Ehesp** [comment]
Seems strange, will investigate it now..

**Comment by dionysiusmarquis** [comment]
+1

**Comment by mlabrum** [comment]
@feelingweird fixed this and submitted a pull request here https://github.com/binggg/react-native-material-design-styles/pull/1 but the pull request has been sitting there...

Maybe @react-native-material-design should fork and bring in this project?

**Comment by Ehesp** [comment]
@mlabrum can you re-submit that PR on here for me and I'll merge it: https://github.com/react-native-material-design/react-native-material-design-styles

Once I've done that, I'll change the package json here to point at this git repo instead and push a new minor version.

**Comment by mlabrum** [comment]
My work colleague has submitted the pull request :) thanks!

**Comment by mlabrum** [comment]
@Ehesp any update? :)

**Comment by Proyoyo** [comment]
I encountered this as well. Can the pull request be merged?

**Comment by feelingweird** [comment]
Hi Proyoyo, 
To get around the issue at the moment we are using this in our bitwise.io build (as a separate step)
`#!/bin/bash

if [ -d "./node_modules/react-native-material-design-styles" ]; then
  rm -Rf ./node_modules/react-native-material-design-styles
else 
  echo "Expected a React Native Material Design Styles node module" 
  exit 1
fi

git clone https://github.com/feelingweird/react-native-material-design-styles.git node_modules/react-native-material-design-styles`

you can also run it from the root of your project locally to fix it.

**Comment by mlabrum** [comment]
This change has now been fixed https://github.com/react-native-material-design/react-native-material-design/pull/51 I think we just need a version bump for the NPM package

**Comment by KGALLET** [comment]
Still having the issue when everything was fine the last 3 days, don't know why

**Comment by casoetan** [comment]
+1

**Comment by Ehesp** [comment]
Can we check with the latest release?

**Comment by cldwalker** [comment]
Was seeing this error on 0.3.3 with the Toolbar but 0.3.5 fixed it. Thanks!

**Comment by Ehesp** [comment]
Cool, I'll close for now!

**Comment by chenop** [comment]
I think this issue relates to 

Here is a [link](https://github.com/binggg/react-native-material-design-styles/issues/2) to the relevant issue

**Comment by miodrage** [comment]
If linking fails you might want to run this:

rn-fetch-blob will not automatically add Android permissions after 0.9.4 please run the following command if you want to add default permissions :

	RNFB_ANDROID_PERMISSIONS=true react-native link
