### ISSUE TITLE
How to get the style for Dropdown buttons

### ISSUE THREAD

**Issue by SamTharani** [react-native-material-design/react-native-material-design#32]
In my application I need a dropdown. Can you help tell me how to get dropdown using react-native material design

**Comment by NoWay1201** [comment]
For now there is no Dropdown in react-native-material-design. Probably you need to write your own or install other and style it.

**Comment by Ehesp** [comment]
There is none, but there is a native component:

https://facebook.github.io/react-native/docs/picker.html#content
