### ISSUE TITLE
Error: attempted to set key .... on an object that is meant to be immutable and has been frozen

### ISSUE THREAD

**Issue by kkgelu** [react-native-material-design/react-native-material-design#33]
Just started introducing the drawer into an existing project, so far it's UI only, I have not given it the navigator or hooked up with any navigation.

The drawer is part of a ViewA with a DrawerLayoutAndroid as root , clicking on a button on View A navigates to View B. View B does not have the drawer. Navigates back from ViewB to ViewA immediately crashes with the error shown in the following screenshot:

![screen shot 2016-03-01 at 06 27 22](https://cloud.githubusercontent.com/assets/11604017/13418669/e5ccc148-df77-11e5-8d1e-3950ea28312e.png)

ViewA code:
```
    render() {
      return (
        <DrawerLayoutAndroid
          drawerWidth={300}
          ref={'DRAWER_REF'}
          drawerPosition={DrawerLayoutAndroid.positions.Left}
          renderNavigationView={() => <DrawerView  />}
        >
       .... some code that can navigate to ViewB
        </DrawerLayoutAndroid>
      );
  },
```

Drawer code:
```
'use strict';

import React, { Component, PropTypes, View, Text, Image } from 'react-native';
import { Avatar, Drawer, Divider, COLOR, TYPO } from 'react-native-material-design';

const styles = {
    header: {
        paddingTop: 16
    },
    text: {
        marginTop: 20
    }
};

var DrawerView = React.createClass({

    getInitialState() {
      return {
        route: null,
      };
    },

    render() {
      const { route } = this.state;

      return (

        <Drawer theme='light'>
                <Drawer.Header image={<Image source={require('./image/nav.jpg')} />}>
                    <View style={styles.header}>
                        <Avatar size={80} image={<Image source={{ uri: "http://facebook.github.io/react-native/img/opengraph.png?2" }}/>} />
                        <Text style={[styles.text, COLOR.paperGrey50, TYPO.paperFontSubhead]}>React Native Material Design</Text>
                    </View>
                </Drawer.Header>

                <Drawer.Section
                    items={[{
                        icon: 'home',
                        value: 'Welcome',
                        active: !route || route === 'welcome',
                        onPress: () => {},
                        onLongPress: () => {}
                    }]}
                />
        </Drawer>

      );
  },

});

module.exports = DrawerView;

```

If I change the <Drawer code to a <Text view, there is no crash with the same steps. I will try this in an isolated the project again later. 

Any help is appreciated!

**Comment by avishayil** [comment]
Hi, I encountered the same error when upgrading to RN 0.21.0-rc.

The solution that I got to so far is here, at my fork.
it's build for my personal use so, I won't recommend using the whole fork, but you can fork the original project and change it accordingly with this specific commit:

https://github.com/avishayil/react-native-material-design/commit/1827032e76676b278c1e8fce283d951e793b2b7b

**Comment by Ehesp** [comment]
Can you make a PR from that? No idea why I used Object assign there.

**Comment by avishayil** [comment]
@Ehesp sure, i'll do that as soon as i'll get to the office.

**Comment by avishayil** [comment]
@Ehesp I sent a PR.

**Comment by kkgelu** [comment]
Thanks! Well done guys, both this awesome component and your quick fix/PR.
