### ISSUE TITLE
Toolbar LeftIcon Ripple Effect

### ISSUE THREAD

**Issue by adnbsr** [react-native-material-design/react-native-material-design#36]
Position of ripple is not properly set.

**Comment by NoWay1201** [comment]
I spotted that too. Don't know if it's like it should be in guidelines, but I fixed it in my Toolbar component (leftIconStyle prop, you just need to set proper margins).

**Comment by Ehesp** [comment]
Is this on Android? Works okay on my demo app version. Which Android & RN version are you guys on?

**Comment by adnbsr** [comment]
Yeah, it is on Android actually. @NoWay1201 we can get rid of this by style but it should be supported by library.

**Comment by NoWay1201** [comment]
Later I will make a PR to fix that, I'm busy right now. But it's simple PR, we just need to change base margins for Icon.

**Comment by NoWay1201** [comment]
PR created #42

**Comment by NoWay1201** [comment]
#42 merged, Issue can be closed.
