### ISSUE TITLE
getColor() returns default color for strings like 'red', 'green' etc.

### ISSUE THREAD

**Issue by farwayer** [react-native-material-design/react-native-material-design#39]

**Comment by NoWay1201** [comment]
Hmm. I don't understand where is your problem. For string 'red' it should return hex of red500 color.

**Comment by farwayer** [comment]
Button is red:
```
<Button text="Hello!" raised={true} overrides={{backgroundColor: '#ff0000'}} />
```

Button is blue:
```
<Button text="Hello!" raised={true} overrides={{backgroundColor: 'red'}} />
```

**Comment by NoWay1201** [comment]
I see your problem. This is because thereis no color like `red` in material palette. You probably want to use `googleRed (100, 300, 500 or 700 - if not specified, it will be 500)` or `paperRed`. The Button is blue, because `PRIMARY` color is `paperBlue`.
