### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by dgilperez** [react-native-material-design/react-native-material-design#4]
Hi! 

Are you planning to release an example app, possible following https://github.com/binggg/MaterialReactNative examples? 

I see you changed a good bunch from original repo, it good be great to have examples (even over documentation).

Thanks!

**Comment by Ehesp** [comment]
Yeah I've got quite a lot to push, which I plan on doing tomorrow.

Also have a demo app which I'm testing on, some examples below... Still a bit of work to do but shouldn't be long.

![image](https://cloud.githubusercontent.com/assets/842078/11919931/37adfe44-a758-11e5-9838-90e171b3b48e.png)

![image](https://cloud.githubusercontent.com/assets/842078/11919964/41873d36-a758-11e5-85d9-ef237bc0817e.png)

![image](https://cloud.githubusercontent.com/assets/842078/11919966/5249497a-a758-11e5-815b-004fb675c6ba.png)

**Comment by dgilperez** [comment]
That looks awesom !!! I'm eager to have a look into it ;)

**Comment by Ehesp** [comment]
I've pushed the changes to 0.2.0-rc - I'll hold off pushing to NPM until I've tested a few more things and got a demo up and running.

**Comment by dgilperez** [comment]
:clap: 

You're fast, man!

**Comment by Ehesp** [comment]
Example app is up: https://github.com/react-native-material-design/demo-app

Need to get it downloadable (I tried quickly but didn't really work).

**Comment by wxyyxc1992** [comment]
It's awesome, Does it work for both ios and android or only android?

**Comment by Ehesp** [comment]
I've not tried it on iOS. Part of the problem is that it uses some Android only React Native things, which of course wouldn't work.
