### ISSUE TITLE
0.3.0 Release

### ISSUE THREAD

**Issue by Ehesp** [react-native-material-design/react-native-material-design#5]
- [x] ~~Swap out Ripple component with [TouchableNativeFeedback](https://facebook.github.io/react-native/docs/touchablenativefeedback.html).~~https://github.com/react-native-material-design/react-native-material-design/commit/042c8970d218eead57056d0ce30c62c3e6a75933
- [x] ~~Create a generic CircularRipple component (for Checkboxes & Radio Buttons)~~ https://github.com/react-native-material-design/react-native-material-design/commit/32a7dc9515e614f4ffd599d506aa207c4c6ad289
- [x] ~~Convert IconButton to IconToggle as per [spec](https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons)~~ https://github.com/react-native-material-design/react-native-material-design/commit/32a7dc9515e614f4ffd599d506aa207c4c6ad289
- [x] ~~Raised Buttons should have elevation - ([spec](https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons))~~ https://github.com/react-native-material-design/react-native-material-design/commit/042c8970d218eead57056d0ce30c62c3e6a75933
- [x] ~~Toolbar should have 4dp elevation by default - ([spec](https://www.google.com/design/spec/components/toolbars.html#toolbars-usage))~~ https://github.com/react-native-material-design/react-native-material-design/commit/4a2b598180c718662f7e67df2c9306ceebd653de
- [x] ~~Drawer menu items are not centered~~ https://github.com/react-native-material-design/react-native-material-design/commit/7c8fef9ee06acca35816ffa4bc312f8541378c19
- [x] ~~Drawer menu items should support labels~~ https://github.com/react-native-material-design/react-native-material-design/commit/917803fd019d853f8008d96ddfa4822fdae05767
- [x] ~~Drawer menu items should be broken into sections to allow for proper padding - ([spec](https://www.google.com/design/spec/patterns/navigation-drawer.html))~~ https://github.com/react-native-material-design/react-native-material-design/commit/b8ccf012136c24e79c4d9fcf64e37df1a7fd7921
- [x] ~~Drawer should respond to theme changes correctly~~ https://github.com/react-native-material-design/react-native-material-design/commit/b8ccf012136c24e79c4d9fcf64e37df1a7fd7921
- [ ] ~~Refactor List component & add to demo~~ Moved to 0.4.0 release
- [x] ~~Avatar should support Image component as a prop, rather than only external images~~ https://github.com/react-native-material-design/react-native-material-design/commit/d038043971a2aeef5b2ac452272d1cb78b20b64f
- [x] ~~Improve counter styling/positioning on IconButton/IconToggle~~ https://github.com/react-native-material-design/react-native-material-design/commit/32a7dc9515e614f4ffd599d506aa207c4c6ad289
- [x] ~~Ensure backward API compatibility with Ripple components (https://github.com/react-native-material-design/react-native-material-design/issues/11)~~ https://github.com/react-native-material-design/react-native-material-design/commit/ea386396f45161f9137b6925f4561f981126f96f

**Comment by bozzmob** [comment]
I wanted to know, what does - " Drawer menu items are not centered" exactly mean?

I see the menu is using the **center** property. And as per the padding and other css property, in the demo app, it looks pretty ok.

```
<View style={styles.item}>
    <Icon
        name={icon}
        color={'rgba(0,0,0,.54)'}
        size={22}
        style={styles.icon}
    />
    <View style={styles.value}>
        <Text style={[TYPO.paperFontBody2, { color: 'rgba(0,0,0,.87)' }]}>
            {value}
        </Text>

    </View>
</View>
```

Style-
```
item: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
```

**Comment by Ehesp** [comment]
The line height is off:

![image](https://cloud.githubusercontent.com/assets/842078/12009573/c1f5fa94-ac75-11e5-9016-6d26d0ebfab4.png)

The icons horizontal does not match with the texts horizontal path.

**Comment by bozzmob** [comment]
Can you please tell me what does - "Drawer menu items should support labels" mean?
I would like to finish up the Drawer enhancements and features, which are like 4 of the tasks.

Basically I am looking forward to be an active contributor to this repo. Would like to help you/your plan in releasing faster :)

**Comment by Ehesp** [comment]
Sure, it's not actually in the spec on [the website](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior), however they are:

![image](https://cloud.githubusercontent.com/assets/842078/12010195/18ff81f6-ac95-11e5-8d49-a9be757daa74.png)

Good place to see them is in the GMail app.

**Comment by bozzmob** [comment]
Got it! :) Thanks for the info.

**Comment by Ehesp** [comment]
Updated!

**Comment by bozzmob** [comment]
Can you shed some light on - "Drawer should respond to theme changes correctly"? What exactly should happen in this?

**Comment by bozzmob** [comment]
Are you referring to changing the image to colour? The image looks good. Doesn't it?

**Comment by Ehesp** [comment]
So you can pass a THEME into the drawer, light and dark. If it's dark the background would be the dark grey color and the text & icons white. Right now the variables are hard coded, so they'd need to adapt to the theme just like Buttons, Checkboxes etc. But yes the image does need changing too.

**Comment by bozzmob** [comment]
Just one final clarification, "If it's dark the background" would mean, if the colour is DARK GREEN or DARK BLUE(etc.,), then, the Drawer's list should switch colour to dark grey background with white fonts & white text?

**Comment by Ehesp** [comment]
It should follow the spec here - I believe the light theme might need some tweaks too.

![image](https://cloud.githubusercontent.com/assets/842078/12011742/18a90532-acd2-11e5-9970-25296c2ad11f.png)

**Comment by bozzmob** [comment]
Hi @Ehesp , I am not sure I can take up the Theme feature for now. But, I would like to give a try on - "Drawer menu items should be broken into sections to allow for proper padding". What sections are we referring to exactly? The components and Config are the 2 sections available right now.

**Comment by Ehesp** [comment]
This one is means that the menu items on the nav drawer are spaced incorrectly. They each have their own margin, but infact they should be broken into groups which have margin, but the items themselves do not.

Problem with the current implementation is that there is just individual menu items, so you cannot group them. See below:

![image](https://cloud.githubusercontent.com/assets/842078/12017466/bf32a1b6-ad4e-11e5-963c-925a107f6ed2.png)

**Comment by bozzmob** [comment]
Woohoo! I guess we are almost in a pretty good shape now! Matter of time, 0.3.0 will be out.
