### ISSUE TITLE
Avatar showing up as square with border radius

### ISSUE THREAD

**Issue by Proyoyo** [react-native-material-design/react-native-material-design#52]
Since commit 71af73d, the <Avatar> in my project is showing up as square with border radius instead of circle. Is this behaviour intended?

Here is how I used the code:
`avatar = <Avatar image = {<Image source = {require('../../everperform-common/assets/default-background.jpg')} />} style = {styles.avatarHeader} size = {110}/>`

`avatarHeader: {
        flex: 1
    }`

**Comment by Ehesp** [comment]
It was actually via this commit I'd imagine: https://github.com/react-native-material-design/react-native-material-design/commit/23980c2ac9ec8029bea36f38893ad5203597e9ca

Looks like there needs be more checks on the borderRadius. 

```
avatar = <Avatar image = {<Image source = {require('../../everperform-common/assets/default-background.jpg')} />} style={styles.avatarHeader} size={110} borderRadius={55} />
```

This should sort you out.
