### ISSUE TITLE
Release 0.3.4

### ISSUE THREAD

**Issue by KGALLET** [react-native-material-design/react-native-material-design#58]
Hi, 

Just to let you know, there are some issues in Release 0.3.4. 

The first one : 
https://github.com/react-native-material-design/react-native-material-design/commit/bd071326ce7ac692fd60087c6845adef4d90715b#commitcomment-17380864

After added the `{`:
 https://github.com/react-native-material-design/react-native-material-design/commit/bd071326ce7ac692fd60087c6845adef4d90715b#commitcomment-17380935 

Thank's 

#55

**Comment by Ehesp** [comment]
Right so I've no idea where processColor has come from...?

**Comment by Ehesp** [comment]
Reverted in 0.3.5 - woops.
