### ISSUE TITLE
[DEMO] Requiring module "DemoApp/src/stores/AppStore.js"

### ISSUE THREAD

**Issue by vincent-the** [react-native-material-design/react-native-material-design#60]
I have pull the Demo App (https://github.com/react-native-material-design/demo-app). Then i run `npm install ` and `react-native run-android`. But after the SplashScreen became this Error: 

`Requiring module "DemoApp/src/stores/AppStore.js" which threw an exceptionhandleException @ ExceptionsManager.js:61 handleError @ InitializeJavaScriptAppEngine.js:80ErrorUtils.reportFatalError @ error-guard.js:28requireImpl @ require.js:42require @ require.js:32(anonymous function) @ index.android.js.js:1messageHandlers.executeApplicationScript @ debuggerWorker.js:18onmessage @ debuggerWorker.js:33
ExceptionsManager.js:61Module AppRegistry is not a registered callable module.`

**Comment by shivam17** [comment]
what was the solution to this problem?

**Comment by juanriglos** [comment]
?
