### ISSUE TITLE
Since 0.25, React API should not be imported from react-native.

### ISSUE THREAD

**Issue by erwan** [react-native-material-design/react-native-material-design#61]
Since 0.25, React API must be imported from 'react', not 'react-native':

https://github.com/facebook/react-native/releases/tag/v0.25.1

That creates warnings and will break in 0.26.

**Comment by miaodonghan** [comment]
Should this change backward compatbile?

**Comment by erwan** [comment]
Yes, the recommended way works in previous versions too.
