### ISSUE TITLE
Not compatible with 0.26

### ISSUE THREAD

**Issue by demiro** [react-native-material-design/react-native-material-design#67]
Getting bunch of errors

> Cannot read property 'oneOf' of undefined

(for CreateIconSet)

and 

> Module AppRegistry is not a registered callable module.

maybe I am doing something wrong?

**Comment by willmcclellan** [comment]
I don't think the npm version of the module got bumped when this change was made:

https://github.com/react-native-material-design/react-native-material-design/commit/a956c864ff5a167808978fc7fa2f15a70ab6540a

You can install from the github repo as a temp fix

**Comment by Ehesp** [comment]
Should now be fixed in 0.3.6... Cheers
