### ISSUE TITLE
Expose the sample apk to users

### ISSUE THREAD

**Issue by bozzmob** [react-native-material-design/react-native-material-design#7]
Hi,

It would be great if you expose the sample apk(I see a project [here](https://github.com/react-native-material-design/demo-app), but add it to this repo in README or docs) of the sample project to the users. You can get more users to really have a feel of the app and start using it.

Few suggestions-

1. Create a robust example app with all features included
2. Release APK
3. Would it be to a good idea make the MaterialIcons a part of this repo itself?

I can also help with PRs. :)

**Comment by Ehesp** [comment]
Hey, 

Yeah I do plan on making the APK from the app, just haven't got around to doing it yet! Feel free to help out with it. I'm working on the core repo atm for 0.3.0 release so would prefer to focus on that

**Comment by bozzmob** [comment]
Sure @Ehesp . Will do the needful and contribute  :+1:

**Comment by Ehesp** [comment]
Nice one - if you do, could you also put the instructions to create the APK too? Perhaps in the README of the demo, cheers!

**Comment by bozzmob** [comment]
I will.

**Comment by bozzmob** [comment]
@Ehesp Can I be added as a collaborator to this repo? I wanted to release the demo apk as discussed.

**Comment by Ehesp** [comment]
Should have an invite.

**Comment by Ehesp** [comment]
@bozzmob Can you update the README with details of how to compile a new APK please.

Also, the APK which is downloaded doesn't work as it's still trying to download the JS bundle... any ideas on how we can compile it to prod?

**Comment by bozzmob** [comment]
@Ehesp Yes, I will attach a production APK today. And I will update instructions in README.

**Comment by Ehesp** [comment]
I've done this now, also for reference the online demo is up at: https://appetize.io/app/hyp1m20y515c16cj5yw2karcjg?device=nexus5&scale=75&orientation=portrait&osVersion=6.0
