### ISSUE TITLE
How to set button's backgroundColor and text color?

### ISSUE THREAD

**Issue by christinwilson** [react-native-material-design/react-native-material-design#73]
I tried this code but the color doesnt change from the default blue.
Button value="LOGIN" raised={true}  theme='dark' overrides={true} backgroundColor='#3fffff' 
@Ehesp could you help me here?

**Comment by Ehesp** [comment]
Can you share some code? Also check out the demo app.

**Comment by christinwilson** [comment]
<Button
value="LOGIN'
raised={true}
theme='dark'
overrides={true}
backgroundColor='#3fffff'
/>

**Comment by GWlodarek** [comment]
@christinwilson try this

<Button
value="LOGIN'
raised={true}
theme='dark'
overrides={{backgroundColor: "3fffff"}}
/>

**Comment by GWlodarek** [comment]
With "<Button" before "value=..."
Sorry about that!

**Comment by christinwilson** [comment]
thanks @GWlodarek . It worked :)

**Comment by kumarks1122** [comment]
Buttons only will take object as styles if we pass object.
We can apply the style for button as following,

apply like ->
`<Button style={styles.buttonStyle}><Text>Login</Text></Button>

const styles = {
    buttonStyle: {
         backgroundColor: "#aaa"
    }
}`

instead of 

`<Button style={styles.buttonStyle}><Text>Login</Text></Button>

const styles = StyleSheet.create({
    buttonStyle: {
        backgroundColor: "#aaa"
    }
})`

**Comment by ibilalbashir** [comment]
please delete react native from this universe. it is made to test your patience, not to develop something

**Comment by ArthurEgide** [comment]
I'm with the same problem. 
Button it's needed to have "title" and put the "<Text>" tag don't change anything because only the title appeas on button box.

**Comment by Typical-dev** [comment]
React native should'nt exist and thats a fact.

**Comment by santhoshkumarvgds** [comment]
<Button
            buttonStyle={{backgroundColor: 'white', color: 'red'}}
            color="red"
            titleStyle={{
              color: '#f75b5b',
            }}
            title="Continue"
            raised={true}
            onPress={storingDomain}
          />
